stages:
  - lint
  - security
  - test
  - build
variables:
  HAPROXY_REGISTRY_GO: "registry.haproxy.com/gophers"
  JUNIT_FILE: "junit-report.xml"
  GOTESTSUM_JUNITFILE: "junit-report.xml"

include:
  - local: .gitlab/lint.yml
  - local: .gitlab/security.yml
  - local: .gitlab/test.yml
  - local: .gitlab/build.yml
