build:
  stage: build
  needs: []
  extends: .all-pipelines
  image:
    name: $HAPROXY_REGISTRY_GO/golang:latest-alpine
    entrypoint: [""]
  tags:
    - go
  before_script:
    - go version
  script:
    - go build -v -o gopherd .
  artifacts:
    paths:
      - gopherd
    expire_in: 1 day
